sudo: false
language: node_js
dist: xenial
services:
  - xvfb

matrix:
  include:
  - node_js: 8
    env: CXX=g++-4.8

script:
  - npm test

addons:
  firefox: 'latest'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
